# Server Configuration
server.port=8080

# Application Name
spring.application.name=api-gateway

# Gateway Routes
spring.cloud.gateway.routes[0].id=student-service-route
spring.cloud.gateway.routes[0].uri=lb://student-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/students/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Global CORS
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# Eureka Client Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=https://sms-eureka-server.onrender.com/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Eureka Instance
eureka.instance.prefer-ip-address=true

# Logging Levels
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.sms.apigateway=DEBUG
