server.port=8761

spring.application.name=eureka-server

# Do not register this server as a client with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.wait-time-in-ms-when-sync-empty=0

# Eureka dashboard
eureka.instance.hostname=localhost

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
